## Default server configuration
---
server:
  applicationConnectors:
    - type: http
      port: 8080
      
 # Database settings.
  database:
      driverClass: org.h2.Driver
      user: test
      password: pass
      url: jdbc:h2:./inmotion/example

